version: '2'
services:
    web:
        container_name: web
        build: ./docker/nginx
        restart: always
        ports:
            - "8001:80"
            - "3000:443"
        volumes:
            - ./:/var/www/html
        depends_on:
            - php

    php:
        container_name: php
        build: ./docker/php
        restart: always
        volumes:
            - ./:/var/www/html